# Generated by Django 6.0.1 on 2026-02-04 18:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(max_length=100, verbose_name='Xizmat')),
                ('description', models.TextField(blank=True, verbose_name='Tavsif')),
                ('status', models.CharField(choices=[('new', 'Yangi'), ('contacted', 'Aloqada'), ('converted', 'Sotildi'), ('rejected', 'Rad etildi')], default='new', max_length=20, verbose_name='Holat')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name="Mas'ul xodim")),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.client', verbose_name='Mijoz')),
            ],
        ),
    ]
